<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="D:\ThangChung\OSS\NUnit2Report_git\Sample\TestSelenium2\bin\Debug\TestSelenium2.dll" total="3" failures="1" not-run="0" date="2010-12-17" time="11:16:38">
  <environment nunit-version="2.4.8.0" clr-version="4.0.30319.1" os-version="Microsoft Windows NT 6.1.7600.0" platform="Win32NT" cwd="D:\ThangChung\OSS\NUnit2Report_git\Libraries\NUnit" machine-name="VLF-THANG" user="T.Chung" user-domain="IBSV" />
  <culture-info current-culture="en-GB" current-uiculture="en-US" />
  <test-suite name="D:\ThangChung\OSS\NUnit2Report_git\Sample\TestSelenium2\bin\Debug\TestSelenium2.dll" success="False" time="30.978" asserts="0">
    <results>
      <test-suite name="TestSelenium1" success="False" time="7.417" asserts="0">
        <results>
          <test-suite name="Scenario0000" success="False" time="7.406" asserts="0">
            <failure>
              <message><![CDATA[System.Net.WebException : Unable to connect to the remote server
  ----> System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it 127.0.0.1:4444]]></message>
              <stack-trace><![CDATA[at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
at System.Net.HttpWebRequest.GetRequestStream()
at Selenium.HttpCommandProcessor.CreateWebRequest(IRemoteCommand command)
at Selenium.HttpCommandProcessor.DoCommand(String command, String[] args)
at Selenium.HttpCommandProcessor.Start()
at Selenium.DefaultSelenium.Start()
at TestSelenium1.Scenario0000.SetupTest() in D:\ThangChung\OSS\NUnit2Report_git\Sample\TestSelenium2\Scenario0000.cs:line 47
--SocketException
at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Int32 timeout, Exception& exception)
]]></stack-trace>
            </failure>
            <results>
              <test-case name="TestSelenium1.Scenario0000.TC001_VerifyDatainCountryLivingSite" executed="True" success="False" time="0.000" asserts="0">
                <failure>
                  <message><![CDATA[TestFixtureSetUp failed in Scenario0000]]></message>
                  <stack-trace />
                </failure>
              </test-case>
            </results>
          </test-suite>
        </results>
      </test-suite>
      <test-suite name="TestSelenium2" success="True" time="23.544" asserts="0">
        <results>
          <test-suite name="Scenario0001" success="True" time="11.202" asserts="0">
            <results>
              <test-case name="TestSelenium2.Scenario0001.TC001_TestSearchGoogleForTheAutomatedTester" executed="True" success="True" time="11.200" asserts="1" />
            </results>
          </test-suite>
          <test-suite name="Scenario0002" success="True" time="12.340" asserts="0">
            <results>
              <test-case name="TestSelenium2.Scenario0002.TC001_TestSearchGoogleForTheAutomatedTester_Firefox" executed="True" success="True" time="12.339" asserts="1" />
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>